version: '3'
services:
  web:
    build: .
    # image: java-redis-app_web 
    ports:
     - "8080:8080"
    networks: 
      - java-redis-network
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks: 
      - java-redis-network  
    command: "redis-server --appendonly yes"
    volumes: 
        - redis-data:/data

volumes: 
    redis-data:
networks: 
    java-redis-network: