version: '3'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    links:
      - redis
  redis:
    image: "redis:4.0.11-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    # command: "redis-server --protected-mode no"
#     volumes: 
#         - redis-data:/data

# volumes: 
#     redis-data:
# networks: 
#     java-redis-network:
#         driver: "bridge"

